# Generated by Django 2.2.6 on 2019-11-10 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('Candidate_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Candidate_name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=150)),
                ('Candidate_Email', models.EmailField(max_length=254)),
                ('Candidate_phn_no', models.PositiveIntegerField()),
                ('No_of_votes', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('Constituency_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Constituency_name', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('Constituency_id', 'Constituency_name')},
            },
        ),
        migrations.CreateModel(
            name='EC_login',
            fields=[
                ('login_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('Party_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Party_name', models.CharField(max_length=50)),
                ('Party_symbol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('Voter_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Voter_name', models.CharField(max_length=50)),
                ('Voter_Phn_no', models.PositiveIntegerField(help_text='Enter a 10 digit number')),
                ('Age', models.PositiveIntegerField()),
                ('Voter_email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Voter_Username', models.CharField(max_length=50, null=True)),
                ('Voter_password', models.CharField(max_length=50, null=True)),
                ('Has_voted', models.BooleanField(default=False)),
                ('ConstituencyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovms.Constituency')),
            ],
            options={
                'unique_together': {('Voter_id', 'ConstituencyID', 'Voter_Username', 'Voter_password')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('Vote_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('CandidateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovms.Candidate')),
                ('Voter_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ovms.Voter')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='ConstituencyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovms.Constituency'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='Party_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ovms.Party'),
        ),
        migrations.CreateModel(
            name='EC_Employee',
            fields=[
                ('Emp_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Emp_Name', models.CharField(max_length=50)),
                ('Ec_Email', models.EmailField(max_length=254)),
                ('login_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ovms.EC_login')),
            ],
            options={
                'unique_together': {('Emp_id', 'login_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('Candidate_id', 'Party_id', 'ConstituencyID')},
        ),
    ]
